/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capitol_1;

/**
 *
 * @author walli
 */
public class GUI extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        n_button = new javax.swing.JButton();
        sqrtn_button = new javax.swing.JButton();
        n2_button = new javax.swing.JButton();
        _2n_button = new javax.swing.JButton();
        logn_button = new javax.swing.JButton();
        nlogn_button = new javax.swing.JButton();
        textField1 = new java.awt.TextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        jProgressBar1.setStringPainted(true);

        n_button.setText("n");
        n_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_buttonActionPerformed(evt);
            }
        });

        sqrtn_button.setText("sqrt(n)");
        sqrtn_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtn_buttonActionPerformed(evt);
            }
        });

        n2_button.setText("n^2");
        n2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2_buttonActionPerformed(evt);
            }
        });

        _2n_button.setText("2^n");
        _2n_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2n_buttonActionPerformed(evt);
            }
        });

        logn_button.setText("log(n)");
        logn_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logn_buttonActionPerformed(evt);
            }
        });

        nlogn_button.setText("n log(n)");
        nlogn_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nlogn_buttonActionPerformed(evt);
            }
        });

        textField1.setText("Quina n vols emprar?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(logn_button)
                .addGap(18, 18, 18)
                .addComponent(sqrtn_button)
                .addGap(18, 18, 18)
                .addComponent(n_button)
                .addGap(18, 18, 18)
                .addComponent(nlogn_button)
                .addGap(12, 12, 12)
                .addComponent(n2_button)
                .addGap(18, 18, 18)
                .addComponent(_2n_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n_button)
                        .addComponent(sqrtn_button)
                        .addComponent(n2_button)
                        .addComponent(_2n_button)
                        .addComponent(logn_button)
                        .addComponent(nlogn_button))
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void inicializar_grafico(){
        
    }
    private void logn_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logn_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logn_buttonActionPerformed

    private void sqrtn_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtn_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqrtn_buttonActionPerformed

    private void n_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_buttonActionPerformed

    private void nlogn_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nlogn_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nlogn_buttonActionPerformed

    private void n2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n2_buttonActionPerformed

    private void _2n_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2n_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__2n_buttonActionPerformed
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _2n_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton logn_button;
    private javax.swing.JButton n2_button;
    private javax.swing.JButton n_button;
    private javax.swing.JButton nlogn_button;
    private javax.swing.JButton sqrtn_button;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
